name: set_variables
run-name: set_variables to ${{ inputs.environment }}

on:
  push:
    branches:
    - '**'
          
jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
        bucket_name: ${{ steps.set_variables.outputs.bucket_name }}
        aws_region: ${{ steps.set_variables.outputs.aws_region }}
        destribution_id: ${{ steps.set_variables.outputs.destribution_id }}
        iam_role: ${{ steps.set_variables.outputs.iam_role }}
        env: ${{ steps.set_variables.outputs.env }}
        deployment: ${{ steps.set_variables.outputs.deployment }}
    steps:
      - id: set_variables
        run: |
          set_output() {
            echo "bucket_name=${VARS[0]}"      >> $GITHUB_OUTPUT
            echo "aws_region=${VARS[1]}"       >> $GITHUB_OUTPUT
            echo "destribution_id=${VARS[2]}"  >> $GITHUB_OUTPUT
            echo "iam_role=${VARS[3]}"         >> $GITHUB_OUTPUT
            echo "env=${VARS[4]}"              >> $GITHUB_OUTPUT
            echo "deployment=${VARS[5]}"       >> $GITHUB_OUTPUT
            echo "list_apps=(bsbs skss snns)"        >> $GITHUB_OUTPUT
          }

          case dev in

          dev)
            export VARS=(ecoplant-front-end us-east-1 E1A8BNKY661F46 arn:aws:iam::173115710334:role/githubAdmin dev development)
            set_output
            ;;

          qa)
            export VARS=(ecoplant-front-end-qa us-east-1 E2PQ2J1MZOJJ3V arn:aws:iam::155580829344:role/githubAdmin qa qa)
            set_output
            ;;

          stage)
            export VARS=(ecoplant-front-end-stage us-east-2 E2D9HTTV0IC9AS arn:aws:iam::444611906471:role/githubAdmin stg staging)
            set_output
            ;;

          prod)
            export VARS=(ecoplant-front-end-prod us-east-1 E3KY2Q4LZRZ8QN arn:aws:iam::444611906471:role/githubAdmin prod production)
            set_output
            ;;

          *)
            echo "No environemt chosen"
            exit 1
            ;;
          esac
      - id: checkvar
        run: |
          echo ${{ steps.set_variables.outputs.env }}
      - id: checklist
        run: |
          echo "nx -p ${{ steps.set_variables.outputs.list_apps }}"

